/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UserController;
import Helper.MessageHelper;
import Model.DBConnection;
import Model.UserModel;
import java.util.Map;
import java.util.Date;
import java.sql.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author luhung
 */
public class RegisterForm extends javax.swing.JFrame {
    DBConnection k = new DBConnection();
    Connection con = k.connection;

    public RegisterForm() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgJenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblNIK = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblBirthDate = new javax.swing.JLabel();
        dcBirthDate = new com.toedter.calendar.JDateChooser();
        lblAgeCategory = new javax.swing.JLabel();
        cbAgeCategory = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        lblPasswordConfirmation = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        rbMan = new javax.swing.JRadioButton();
        rbWoman = new javax.swing.JRadioButton();
        lblPhoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaAddress = new javax.swing.JTextArea();
        btnRegister = new javax.swing.JButton();
        lblSudahMemiliki = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jpPasswordConfirmation = new javax.swing.JPasswordField();
        jpPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblLogin1 = new javax.swing.JLabel();
        lblNIK1 = new javax.swing.JLabel();
        txtNIK1 = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        lblBirthDate1 = new javax.swing.JLabel();
        dcBirthDate1 = new com.toedter.calendar.JDateChooser();
        lblAgeCategory1 = new javax.swing.JLabel();
        cbAgeCategory1 = new javax.swing.JComboBox<>();
        lblPassword2 = new javax.swing.JLabel();
        jpPassword2 = new javax.swing.JPasswordField();
        lblPasswordConfirmation1 = new javax.swing.JLabel();
        lblGender1 = new javax.swing.JLabel();
        rbMan1 = new javax.swing.JRadioButton();
        rbWoman1 = new javax.swing.JRadioButton();
        lblPhoneNumber1 = new javax.swing.JLabel();
        txtPhoneNumber1 = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaAddress1 = new javax.swing.JTextArea();
        btnRegister1 = new javax.swing.JButton();
        lblSudahMemiliki1 = new javax.swing.JLabel();
        lblRegister1 = new javax.swing.JLabel();
        lblPassword3 = new javax.swing.JLabel();
        jpPassword3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(648, 620));

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setFont(new java.awt.Font("GE Inspira", 1, 48)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("REGISTER");
        lblLogin.setToolTipText("");

        lblNIK.setBackground(new java.awt.Color(255, 255, 255));
        lblNIK.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblNIK.setForeground(new java.awt.Color(255, 255, 255));
        lblNIK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNIK.setText("NIK");
        lblNIK.setToolTipText("");

        txtNIK.setName(""); // NOI18N
        txtNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIKActionPerformed(evt);
            }
        });

        lblName.setBackground(new java.awt.Color(255, 255, 255));
        lblName.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Nama");
        lblName.setToolTipText("");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblBirthDate.setBackground(new java.awt.Color(255, 255, 255));
        lblBirthDate.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBirthDate.setText("Tgl Lahir");
        lblBirthDate.setToolTipText("");

        lblAgeCategory.setBackground(new java.awt.Color(255, 255, 255));
        lblAgeCategory.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblAgeCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblAgeCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAgeCategory.setText("Kategori Usia");
        lblAgeCategory.setToolTipText("");

        cbAgeCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anak", "Remaja", "Dewasa", "Lanjut Usia" }));
        cbAgeCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgeCategoryActionPerformed(evt);
            }
        });

        lblPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password");
        lblPassword.setToolTipText("");

        lblPasswordConfirmation.setBackground(new java.awt.Color(255, 255, 255));
        lblPasswordConfirmation.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblPasswordConfirmation.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordConfirmation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasswordConfirmation.setText("<html>Konfirmasi<br>Password<html>");
        lblPasswordConfirmation.setToolTipText("");

        lblGender.setBackground(new java.awt.Color(255, 255, 255));
        lblGender.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender.setText("Jenis Kelamin");
        lblGender.setToolTipText("");

        rbMan.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        rbMan.setForeground(new java.awt.Color(255, 255, 255));
        rbMan.setSelected(true);
        rbMan.setText("Pria");
        rbMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbManActionPerformed(evt);
            }
        });

        rbWoman.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        rbWoman.setForeground(new java.awt.Color(255, 255, 255));
        rbWoman.setText("Wanita");
        rbWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWomanActionPerformed(evt);
            }
        });

        lblPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhoneNumber.setText("No Telp.");
        lblPhoneNumber.setToolTipText("");

        txtPhoneNumber.setText("08");
        txtPhoneNumber.setToolTipText("");
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddress.setText("Alamat");
        lblAddress.setToolTipText("");

        txtaAddress.setColumns(20);
        txtaAddress.setRows(5);
        jScrollPane1.setViewportView(txtaAddress);

        btnRegister.setFont(new java.awt.Font("GE Inspira", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblSudahMemiliki.setBackground(new java.awt.Color(255, 255, 255));
        lblSudahMemiliki.setFont(new java.awt.Font("GE Inspira", 1, 14)); // NOI18N
        lblSudahMemiliki.setForeground(new java.awt.Color(255, 255, 255));
        lblSudahMemiliki.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSudahMemiliki.setText("Login");
        lblSudahMemiliki.setToolTipText("");

        lblRegister.setBackground(new java.awt.Color(255, 255, 255));
        lblRegister.setFont(new java.awt.Font("GE Inspira", 1, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRegister.setText("Sudah memiliki akun ?");
        lblRegister.setToolTipText("");

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("Username");
        lblUsername.setToolTipText("");

        jpPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSudahMemiliki)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNumber)
                            .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPhoneNumber)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbMan)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGender)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtNIK)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbWoman)
                                            .addComponent(dcBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblAgeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbAgeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpPasswordConfirmation, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jpPassword)
                                    .addComponent(txtUsername))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAgeCategory)
                        .addComponent(cbAgeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbWoman)
                            .addComponent(rbMan))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jpPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPasswordConfirmation))))
                .addGap(63, 63, 63)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSudahMemiliki, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setPreferredSize(new java.awt.Dimension(648, 620));

        lblLogin1.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin1.setFont(new java.awt.Font("GE Inspira", 1, 48)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin1.setText("REGISTER");
        lblLogin1.setToolTipText("");

        lblNIK1.setBackground(new java.awt.Color(255, 255, 255));
        lblNIK1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblNIK1.setForeground(new java.awt.Color(255, 255, 255));
        lblNIK1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNIK1.setText("NIK");
        lblNIK1.setToolTipText("");

        txtNIK1.setName(""); // NOI18N
        txtNIK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIK1ActionPerformed(evt);
            }
        });

        lblName1.setBackground(new java.awt.Color(255, 255, 255));
        lblName1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName1.setText("Nama");
        lblName1.setToolTipText("");

        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        lblBirthDate1.setBackground(new java.awt.Color(255, 255, 255));
        lblBirthDate1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblBirthDate1.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthDate1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBirthDate1.setText("Tgl Lahir");
        lblBirthDate1.setToolTipText("");

        lblAgeCategory1.setBackground(new java.awt.Color(255, 255, 255));
        lblAgeCategory1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblAgeCategory1.setForeground(new java.awt.Color(255, 255, 255));
        lblAgeCategory1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAgeCategory1.setText("Kategori Usia");
        lblAgeCategory1.setToolTipText("");

        cbAgeCategory1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anak", "Remaja", "Dewasa", "Lanjut Usia" }));
        cbAgeCategory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAgeCategory1ActionPerformed(evt);
            }
        });

        lblPassword2.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword2.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblPassword2.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword2.setText("Password");
        lblPassword2.setToolTipText("");

        lblPasswordConfirmation1.setBackground(new java.awt.Color(255, 255, 255));
        lblPasswordConfirmation1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblPasswordConfirmation1.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordConfirmation1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPasswordConfirmation1.setText("<html>Konfirmasi<br>Password<html>");
        lblPasswordConfirmation1.setToolTipText("");

        lblGender1.setBackground(new java.awt.Color(255, 255, 255));
        lblGender1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblGender1.setForeground(new java.awt.Color(255, 255, 255));
        lblGender1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender1.setText("Jenis Kelamin");
        lblGender1.setToolTipText("");

        rbMan1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        rbMan1.setForeground(new java.awt.Color(255, 255, 255));
        rbMan1.setSelected(true);
        rbMan1.setText("Pria");
        rbMan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMan1ActionPerformed(evt);
            }
        });

        rbWoman1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        rbWoman1.setForeground(new java.awt.Color(255, 255, 255));
        rbWoman1.setText("Wanita");
        rbWoman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbWoman1ActionPerformed(evt);
            }
        });

        lblPhoneNumber1.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblPhoneNumber1.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhoneNumber1.setText("No Telp.");
        lblPhoneNumber1.setToolTipText("");

        txtPhoneNumber1.setText("08");
        txtPhoneNumber1.setToolTipText("");
        txtPhoneNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumber1ActionPerformed(evt);
            }
        });

        lblAddress1.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress1.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddress1.setText("Alamat");
        lblAddress1.setToolTipText("");

        txtaAddress1.setColumns(20);
        txtaAddress1.setRows(5);
        jScrollPane2.setViewportView(txtaAddress1);

        btnRegister1.setFont(new java.awt.Font("GE Inspira", 1, 18)); // NOI18N
        btnRegister1.setText("Register");
        btnRegister1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegister1MouseClicked(evt);
            }
        });
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });

        lblSudahMemiliki1.setBackground(new java.awt.Color(255, 255, 255));
        lblSudahMemiliki1.setFont(new java.awt.Font("GE Inspira", 1, 14)); // NOI18N
        lblSudahMemiliki1.setForeground(new java.awt.Color(255, 255, 255));
        lblSudahMemiliki1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSudahMemiliki1.setText("Login");
        lblSudahMemiliki1.setToolTipText("");

        lblRegister1.setBackground(new java.awt.Color(255, 255, 255));
        lblRegister1.setFont(new java.awt.Font("GE Inspira", 1, 14)); // NOI18N
        lblRegister1.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRegister1.setText("Sudah memiliki akun ?");
        lblRegister1.setToolTipText("");

        lblPassword3.setBackground(new java.awt.Color(255, 255, 255));
        lblPassword3.setFont(new java.awt.Font("GE Inspira", 1, 16)); // NOI18N
        lblPassword3.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword3.setText("Username");
        lblPassword3.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblRegister1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSudahMemiliki1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPasswordConfirmation1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPassword3)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhoneNumber1)
                                    .addComponent(lblAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPhoneNumber1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbMan1)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblGender1)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblNIK1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblBirthDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(51, 51, 51)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtName1)
                                                .addComponent(txtNIK1)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(rbWoman1)
                                                        .addComponent(dcBirthDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblAgeCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbAgeCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)
                                            .addComponent(jpPassword2)))
                                    .addComponent(lblPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIK1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAgeCategory1)
                        .addComponent(cbAgeCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcBirthDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirthDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbWoman1)
                            .addComponent(rbMan1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhoneNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPhoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword3))
                .addGap(18, 18, 18)
                .addComponent(lblPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblPasswordConfirmation1)
                .addGap(23, 23, 23)
                .addComponent(jpPassword3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSudahMemiliki1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        rbgJenisKelamin.add(rbMan);
        rbgJenisKelamin.add(rbWoman);
        Date defaultDate = new Date();
        dcBirthDate.setDate(defaultDate);
    }//GEN-LAST:event_formWindowOpened

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // TODO add your handling code here:

        String gender = rbMan.isSelected() ? rbMan.getText() : rbWoman.getText();
        if(!jpPassword.getText().equals(jpPasswordConfirmation.getText())) {
            MessageHelper.showWarning("Password konfirmasi tidak sesuai");
            return;
        }
        
        Date bd = dcBirthDate.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String birthDate = sdf.format(bd);

        String[] userData = new String[]{
            txtNIK.getText(),
            txtName.getText(),
            birthDate,
            cbAgeCategory.getSelectedItem().toString(),
            gender,
            txtPhoneNumber.getText(),
            txtaAddress.getText(),
            txtUsername.getText(),
            jpPassword.getText(),
        };
        
//        for (int i = 0; i < userData.length; i++) {
//            System.out.println("Element " + i + ": " + userData[i]);
//        }

        UserController userController = new UserController();
        Map<String, Object> result = userController.store(userData);
        MessageHelper.showMessageFromResult(result);
        
        if (Boolean.TRUE.equals(result.get("status"))) {
            this.dispose(); 
            new LoginForm().setVisible(true); 
        }
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void rbWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWomanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWomanActionPerformed

    private void rbManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbManActionPerformed

    private void cbAgeCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgeCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgeCategoryActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIKActionPerformed

    private void txtNIK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIK1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIK1ActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void cbAgeCategory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAgeCategory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAgeCategory1ActionPerformed

    private void rbMan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMan1ActionPerformed

    private void rbWoman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbWoman1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbWoman1ActionPerformed

    private void txtPhoneNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumber1ActionPerformed

    private void btnRegister1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegister1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegister1MouseClicked

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void jpPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JComboBox<String> cbAgeCategory;
    private javax.swing.JComboBox<String> cbAgeCategory1;
    private com.toedter.calendar.JDateChooser dcBirthDate;
    private com.toedter.calendar.JDateChooser dcBirthDate1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JPasswordField jpPassword2;
    private javax.swing.JPasswordField jpPassword3;
    private javax.swing.JPasswordField jpPasswordConfirmation;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAgeCategory;
    private javax.swing.JLabel lblAgeCategory1;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblBirthDate1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblNIK;
    private javax.swing.JLabel lblNIK1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword2;
    private javax.swing.JLabel lblPassword3;
    private javax.swing.JLabel lblPasswordConfirmation;
    private javax.swing.JLabel lblPasswordConfirmation1;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRegister1;
    private javax.swing.JLabel lblSudahMemiliki;
    private javax.swing.JLabel lblSudahMemiliki1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JRadioButton rbMan;
    private javax.swing.JRadioButton rbMan1;
    private javax.swing.JRadioButton rbWoman;
    private javax.swing.JRadioButton rbWoman1;
    private javax.swing.ButtonGroup rbgJenisKelamin;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNIK1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumber1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextArea txtaAddress;
    private javax.swing.JTextArea txtaAddress1;
    // End of variables declaration//GEN-END:variables
}
